apiVersion: v1
kind: Namespace
metadata:
  name: log-explorer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-explorer
  namespace: log-explorer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-explorer
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-explorer
subjects:
- kind: ServiceAccount
  name: log-explorer
  namespace: log-explorer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-explorer-config
  namespace: log-explorer
data:
  config.yaml: |
    kubernetes:
      config_file: null  # Use in-cluster config
      namespace: default

    logging:
      level: INFO
      context_lines: 3
      max_lines: 1000

    web:
      host: 0.0.0.0
      port: 5000
      debug: false

    search:
      java_error_patterns:
        - "Exception"
        - "Error"
        - "Caused by"
        - "at\\s+[a-zA-Z0-9_$]+\\.[a-zA-Z0-9_$]+\\("
      
      context_patterns:
        - "\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}"
        - "\\[.*?\\]"
        - "ERROR|WARN|INFO|DEBUG|TRACE"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-explorer
  namespace: log-explorer
  labels:
    app: log-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-explorer
  template:
    metadata:
      labels:
        app: log-explorer
    spec:
      serviceAccountName: log-explorer
      containers:
      - name: log-explorer
        image: log-explorer:latest  # Replace with your image
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: web
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: log-explorer-config

---
apiVersion: v1
kind: Service
metadata:
  name: log-explorer
  namespace: log-explorer
  labels:
    app: log-explorer
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: web
  selector:
    app: log-explorer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-explorer
  namespace: log-explorer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Add SSL and other annotations as needed
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # tls:
  # - hosts:
  #   - log-explorer.yourdomain.com
  #   secretName: log-explorer-tls
  rules:
  - host: log-explorer.local  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-explorer
            port:
              number: 80